[core]
repositories = ["jdrouet/inapt"]

[github]
base_url = "https://api.github.com"
# max_retry = 5
# timeout = 60
# token = "..."

[http_server]
address = "0.0.0.0"
port = 3000

[pgp_cipher]
private_key_path = "/etc/inapt/private-key.pem"
# passphrase = "..."

[storage]
path = "/var/lib/inapt/inapt.db"

[worker]
interval = 43200 # 12h
